### PR TITLE
Added option to log-scale the x-axis in the Forest Plot.

### PR DESCRIPTION
**Pull request by oldschoolcool2**
Thanks for the great SHINY app! I thought it might be useful to demonstrate the x-axis on the log-scale and added an option in the package to do so.

### CODE REVIEW

**Comment by smouksassi** [comment]
thanks for the PR the checks are failing on Travis will review tomrrow

**Comment by smouksassi** [comment]
Thanks again but I am not sure what really changed the diffs are like all the code has been deleted and added back so very hard to pin point what argument and edits you made can you reissue the PR with the diffs and updated docs so I can review and merge and please make  sure that Travis is not failing

**Comment by smouksassi** [comment]
Hi @Ruminare I included your suggestions in the latest commit. I could not merge due to conflicts I changed how you implemented loggin of x axis to scale_x_cont .. ( trans = "log") to avoir losing custom ticks etc.
Let me know if this works for you.
Samer

**Comment by oldschoolcool2** [comment]
Thanks @smouksassi ! I have no idea why the commit didn't show only the diffs, but glad you were able to see what I did and make the change! I appreciate it!

**Pull request closed without merging**
